#!/usr/bin/env ruby

raise "Not the right place #{Dir.pwd}" unless File.directory?('lib')

scripts = (Dir['lib/*.rb'] + Dir['lib/**/*']).uniq
scripts = scripts.reject{ |f| File.directory?(f) }

# We don't want the rake helper.
scripts = scripts - ["lib/setup/rake.rb"]
scripts = scripts + ["bin/setup.rb"]

#
bundle = ""

# insert scripts
scripts.each do |script|
  bundle << "\n\n# %-16s #{"#" * 60}\n\n" % File.basename(script)
  bundle << File.read(script)
end

# remove setup requires
bundle.gsub!(/require\s+["']setup\/(.*?)["']\s*$/, '')

# remove blank lines
bundle.gsub!(/^\s*\n/, '')

# remove comments
bundle.gsub!(/^\s*\#.*?\n/, '')

# save
File.open('script/setup', 'w') do |f|
  f << "#!/usr/bin/env ruby\n"
  f << bundle
end

FileUtils.chmod(0744, 'script/setup')
